apiVersion: v1
kind: Service
metadata:
  name: wc-python-service
spec:
  type: NodePort
  selector:
    app: wc-python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
